# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Review-Journal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Review-Journal
  pod 'Firebase/Database'

  target 'Review-JournalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Review-JournalUITests' do
    # Pods for testing
  end

end
